### PR TITLE
A complete refactor

### LINKED ISSUE #5: Create nice index page
The default page shouldn't be an example one, but the one with the list of all available slides.

Also, a nice thing could be done: when there are no new custom slides, there should be links to examples, docs and some introduction/setup-like text, so when you'll clone the project for the first time you'll see all those example/placeholder things.

But if you'll add your custom slides, they would appear there replacing placeholder content (however, there should be some link to those content, like a small “tutorial” link at the bottom or something like this)

### LINKED ISSUE #7: Create example pages
There should be a folder with examples, genetared by the jekyll and showing all the possible things you could set up.

So, this should be basically those examples from the shower and its themes.

### LINKED ISSUE #16: Markup for figure with captions
Which syntax to use? Markdown don't have anything for this, so for quotes (with figure-figcaption) we need now to use this kind of syntax:

``` HTML
<figure markdown="1">

> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia.

<figcaption>Marcus Tullius Cicero</figcaption>
</figure>
```

And that's not that cool.

### LINKED ISSUE #34: Merging classes
Right now slides could either get autogenerated classes, or have them set in md. But we always would want to have `slide` class etc, so it would be nice to merge classes defined in different ways.

### PR DESCRIPTION
**Pull request by aidistan**
Shower is great but building from HTML is too trivial. Jekyller hadn't been updated since March, leaving, as @kizu said,

> a lot of things to refactor

With these commits, we have a completely-reviewed-and-refactored Jekyller. Here is a done list:
- Update all the submodules, namely `shower/core`, `shower/ribbon` and `shower/bright`
- Update __config.yml_ to catch up Jekyll's changement (also fix issue #32)
- Add .slide automatically for all sections in layout, leave others to be added manually in markdown (fix #34 and #8)
- Implement figcaptions in the way metioned by @pepelsbey (fix #16)
- No syntax for `<mark>`, but to highlight codes by pygments (related to #14)
- Use collections to manage all examples and slides (fix #7), and create a index page of them (fix #5).

I kept all the docs unchanged and look forward to your suggestions.

### CODE REVIEW

**Comment by aidistan** [comment]
Is this repo still alive? @pepelsbey

**Comment by kizu** [comment]
Yes, sorry for waiting, I'm just too busy right now, I'll try to find some time to check all the things you've done there and if all would be ok, I'll merge it. Thanks for the PR :)

**Comment by aidistan** [comment]
That's great. Thanks for replying.

**Comment by dm4** [comment]
thanks @aidistan and @kizu :+1:

**Pull request closed without merging**
